### ISSUE TITLE
_fqname

### ISSUE THREAD

**Issue by hashbomb** [helloitsm3/buildspace-solutions#8]
![image](https://user-images.githubusercontent.com/94155502/189635961-668093ae-4a68-4391-9560-9552b06e6843.png)
npx hardhat run scripts/run.js the problem like this, how to fix?

**Comment by helloitsm3** [comment]
> ![image](https://user-images.githubusercontent.com/94155502/189635961-668093ae-4a68-4391-9560-9552b06e6843.png) npx hardhat run scripts/run.js the problem like this, how to fix?

Sorry for the late reply. I've already fixed this in the Polygon project. Do take a look at it
